all:
	g++ serverTCP.cpp -o serverTCP
	g++ clientTCP.cpp -o clientTCP
	g++ serverUDP.cpp -o serverUDP
	g++ clientUDP.cpp -o clientUDP
	g++ chatServer.cpp -o chatServer
	g++ chatClient.cpp -o chatClient

clean:
	rm serverTCP clientTCP serverUDP clientUDP chatServer chatClient