# Stage 1: Build
FROM gcc:14 AS build

# Set working directory
WORKDIR /app

# Copy source files to the container
COPY main.cpp .

# Compile the program
RUN g++ -o myapp main.cpp

# Stage 2: Production
FROM ubuntu:24.04 AS production

# Set working directory
WORKDIR /app

# Copy the binary from the build stage
COPY --from=build /app/myapp .

