apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
# Above is equivalent to:
# kubectl expose pod nginx-pod --type=NodePort --port=80
  selector:
    app: nginx