apiVersion: v1
kind: Pod
metadata:
  name: heavy-api
  namespace: dev
  labels:
    app: heavy-api
spec:
  containers:
  - name: heavy-api
    image: lmacademy/color-api:1.1.0
    resources:
      requests:
        cpu: '1'
        memory: '1Gi'
      limits:
        cpu: '2'
        memory: '2Gi'
    ports:
      - containerPort: 80
